import type { Metadata } from "next";
import { Baloo_Bhai_2 } from "next/font/google";
import "./globals.css";
import Provider from "./provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const baloo = Baloo_Bhai_2({subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={baloo.className}
      >
        <Provider>
          {children} 
        </Provider>
        
      </body>
    </html>
  );
}
